### PR TITLE
Add Google Wavenet

### PR DESCRIPTION
**Pull request by Romkabouter**
This is the first part, needed for wavenet. 
Also, a PR will be opened for other repo's.

I do not know if this is the correct procedure by the way.

### CODE REVIEW

**Comment by koenvervloesem** [comment]
Can you do a `make reformat` and commit the changes to fix the code style issues?

**Comment by Romkabouter** [comment]
> Can you do a `make reformat` and commit the changes to fix the code style issues?

That gives me a "scripts/format-code.sh rhasspysupervisor/*.py *.py
scripts/format-code.sh: line 16: black: command not found
make: *** [Makefile:32: reformat] Error 127
"
I am on a debian buster VM. I'll see if I can fixe the issues

edit: I see I need to install some extra packages.

**Comment by Romkabouter** [comment]
Hmm, I got this error on my Mac as well:
"architecture.sh: line 17: declare: -A: invalid option"

How to fix it? I did not change that file.

**Comment by koenvervloesem** [comment]
What's your bash version? I think the -A flag is fairly recent.

**Comment by Romkabouter** [comment]
> What's your bash version? I think the -A flag is fairly recent.

I have updated my bash and it work on my mac now, but obviously the tests still fail

**Comment by koenvervloesem** [comment]
Ok, this was already broken before your pull request, I fixed it in https://github.com/rhasspy/rhasspy-supervisor/commit/ebf899b197a5aff0d0904e3f8b691d0cd34b1ac0.

By the way, what do you mean by "I do not know if this is the correct procedure by the way."?

**Comment by Romkabouter** [comment]
> Ok, this was already broken before your pull request, I fixed it in [ebf899b](https://github.com/rhasspy/rhasspy-supervisor/commit/ebf899b197a5aff0d0904e3f8b691d0cd34b1ac0).
> 
> By the way, what do you mean by "I do not know if this is the correct procedure by the way."?

Well, I have a change in superviser, but also in server and I want to add an extra submodule.
I will ask on the forum ;)

**Pull request merged**
